config/routes.rb
Rails.application.routes.draw do  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html  
  # Defines the root path route ("/")
  # root "articles#index"
  
  devise_for :users
  
  resources :listings do
    resources :stocks
  end

  root to: 'pages#index'  

  get   '/portfolio' => 'pages#portfolio', as: 'portfolio'
  get   '/new' => 'pages#new', as: 'new_trader'
  get   '/user/:id' => 'pages#show', as: 'user'
  patch '/user/:id' => 'pages#update'
  get   '/user/:id/edit' => 'pages#edit', as: 'user_edit'
  post  '/' => 'pages#create'  
  get   '/confirm_user/:trader_id' => 'pages#confirm_user', as: 'confirm_user'
  get   '/balance' => 'pages#balance', as: 'balance'
  patch '/balance' => 'pages#add_money'

  get   '/listings/:listing_id/buy', to: 'stocks#buy', as: 'buy_stock'
  get   '/listings/:listing_id/sell', to: 'stocks#sell', as: 'sell_stock'

  get   '/trader/transactions' => 'transactions#index', as: 'transactions'
  get   '/trader/transactions/:id' => 'transactions#show', as: 'transaction'
  
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user

end

app/models/stock.rb
class Stock < ApplicationRecord
    validates :quantity, presence: true
    belongs_to :listing
    after_save :delete_zero_quantity
    
    def delete_zero_quantity
        if self.quantity == 0
            self.delete            
        end
    end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :authenticate_user!
  before_action :get_listing
  before_action :set_stock, only: %i[ show edit update destroy ]
  load_and_authorize_resource

  def buy  
    @stock_build = @listing.stocks.build  
    @stock = Stock.find_by(user_id: current_user.id, listing_id: @listing.id)
    @existing = @stock != nil ? true : false   
  end

  def sell
    @stock = Stock.find_by(user_id: current_user.id, listing_id: @listing.id)
  end 

  def index
    @stocks = @listing.stocks.where(user_id: current_user.id)
  end

  def show
  end
  
  def new        
    @stock = @listing.stocks.build
  end

  def edit
  end

  def create
    @current_balance = User.find(current_user.id).balance || 0
    @quantity = params[:stock][:quantity].to_i
    @total_price = @listing.price * @quantity
    @new_balance = @current_balance - @total_price
    @stock = Stock.new(
      user_id: current_user.id,
      listing_id: @listing.id,
      quantity: @quantity
    )
    @transaction = Transaction.new(
        name: @listing.name,
        ticker: @listing.ticker,
        quantity: @quantity,
        price: @total_price,
        user_id: current_user.id,
        transaction_type: 'Buy'
    )

    if @current_balance > @total_price
      @stock.save!
      User.find(current_user.id).update(balance: @new_balance)
      @transaction.save!
      redirect_to portfolio_path
    else
      redirect_to buy_stock_path(@listing.id, notice: 'Insufficient Balance')
    end

    # @stock = @listing.stocks.build(stock_params)

    # respond_to do |format|
    #   if @stock.save
    #     format.html { redirect_to portfolio_path, notice: "Stock was successfully created." }
    #     format.json { render :show, status: :created, location: @stock }
    #   else
    #     format.html { render :new, status: :unprocessable_entity }
    #     format.json { render json: @stock.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  def update
    @current_quantity = User.find(current_user.id).stocks.find_by(listing_id: @listing.id).quantity
    @current_balance = User.find(current_user.id).balance || 0
    @quantity = params[:quantity].to_i
    @total_price = @listing.price * @quantity
    @new_balance = @current_balance - @total_price
    @transaction = Transaction.new(
        name: @listing.name,
        ticker: @listing.ticker,
        quantity: @quantity,
        price: @total_price,
        user_id: current_user.id,
        transaction_type: nil
    )

    if params[:transaction_type] == 'buy'
      if @current_balance < @total_price
        redirect_to buy_stock_path(@listing.id, notice: 'Insufficient Balance')
      else
        @total_quantity = (@stock.quantity + @quantity)    
        @stock.update(quantity: @total_quantity)
        User.find(current_user.id).update(balance: @new_balance)
        @transaction.transaction_type = 'Buy'
        @transaction.save!
        redirect_to portfolio_path
      end
    else
      if @current_quantity < @quantity
        redirect_to sell_stock_path(@listing.id, notice: 'Insufficient quantity')
      else
        @new_balance = @current_balance + @total_price
        @total_quantity = (@stock.quantity - @quantity)
        @stock.update(quantity: @total_quantity)
        User.find(current_user.id).update(balance: @new_balance)
        @transaction.transaction_type = 'Sell'
        @transaction.save!  
        redirect_to portfolio_path
      end
    end

    

  end

  def destroy
    @stock.destroy

    respond_to do |format|
      format.html { redirect_to listing_stocks_path(@listing), notice: "Stock was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    def get_listing
      @listing = Listing.find(params[:listing_id])
    end

    def set_stock
      @stock = @listing.stocks.find(params[:id])
    end

    def stock_params
      params.require(:stock).permit(:quantity, :listing_id, :user_id)
    end
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/stocks/_form.html.erb
<%= stylesheet_link_tag "dashboard", "data-turbo-track": "reload" %>

 <body>

<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#"><span>Hi </span><%= current_user.first_name.capitalize %>!</a>
  <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <input id='myInput' onkeyup="myFunction()" class="form-control form-control-dark w-100" type="text" placeholder="Search by Stock Name" aria-label="Search">

  <div class="navbar-nav">
    <div class="nav-item text-nowrap">
       <%= button_to "Log out", destroy_user_session_path, :method => :delete, class:'nav-link px-3 btn' %>
    </div>
  </div>
</header>

<div class="container-fluid">
  <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="position-sticky pt-3">

      <% if current_user.role == 'trader'%>
        <ul class="nav flex-column">
        <li class="nav-item">
            <%= link_to root_path, class:'nav-link' do %>
              <span data-feather="home"></span>
              Dashboard
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to portfolio_path, class: "nav-link" do%>
              <span data-feather="file"></span>
              Portfolio
             <%end%>
          </li>
           <li class="nav-item">
            <%= link_to listings_path, class: "nav-link" do%>
              <span data-feather="file"></span>
              Listings
             <%end%>
          </li>
           <li class="nav-item">
            <%= link_to transactions_path, class: "nav-link" do%>
              <span data-feather="file"></span>
              Transaction History
             <%end%>
          </li>
          <li class="nav-item">
          <%= link_to balance_path, class: "nav-link" do%>
            <span data-feather="dollar-sign"></span>
              Balance 
            <span data-feather="plus-circle"></span>
            <span><%= number_to_currency current_user.balance %></span>
            <%end%>
          </li>
        </ul>
        <%end%>

        <% if current_user.role == 'admin' %>
        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
          <span>Admin</span>
        </h6>
        <ul class="nav flex-column mb-2">
          <li class="nav-item">
             <a class="nav-link" href="/#pendingUser">
              <span data-feather="users"></span>
              <span>Pending Users</span>
              <span class="position-absolute end-5px pending"><%= get_pending_users %></span>
            </a>
          </li>
          <li class="nav-item">
              <a class="nav-link" href="/new">
              <span data-feather="users"></span>
              Create a Trader
            </a>
          </li>
          <li class="nav-item">
            <%= link_to transactions_path, class: 'nav-link' do%>
              <span data-feather="file-text"></span>
              Transactions
            <%end%>
          </li>
        </ul>
        <% end %>
      </div>
    </nav>

    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
<h1><%= @listing.name%></h1>
    
      </div>

     <div id='fundsError' class='d-none justify-content-center align-item-center'>
     <span class='text-danger fw-bold '>Insufficient Funds!</span>
     </div>
     

<section class="h-100 gradient-custom">
  <div class="container py-5">
    <div class="row d-flex justify-content-center my-4">
      <div class="col-md-8">
        <div class="card mb-4">
          <div class="card-header py-3">
            <h5 class="mb-0">You are <span class='btn btn-primary'> Buying </span></h5>
          </div>
          <div class="card-body">
            <!-- Single item -->
            <div class="row">
              <div class="col-lg-3 col-md-12 mb-4 mb-lg-0">
                <!-- Image -->
                <div class="bg-image hover-overlay hover-zoom ripple rounded" data-mdb-ripple-color="light">
                  <img src="<%= @listing.logo %>"
                    class="w-100" alt="Blue Jeans Jacket" />
                  <a href="#!">
                    <div class="mask" style="background-color: rgba(251, 251, 251, 0.2)"></div>
                  </a>
                </div>
                <!-- Image -->
              </div>

              <div class="col-lg-5 col-md-6 mb-4 mb-lg-0">
                <!-- Data -->
                <p><strong><%= @listing.ticker%></strong></p>
                <p>Earning Ratio: <span class='bg-success text-white px-2 py-1 rounded fw-bold'><%= @listing.pe_ratio %></span></p>
                <p>Price: <span id='staticPrice'><%= number_to_currency @listing.price%></span></p>
                <p>Previous Price: <%= number_to_currency @listing.previous_close%></p>
          
               
                <!-- Data -->
              </div>

              <div class="col-lg-4 col-md-6 mb-4 mb-lg-0 d-flex flex-column justify-content-center">
                <!-- Quantity -->


                <div class="d-flex mb-4" style="max-width: 300px">
                  <button class="btn btn-primary px-3 me-2 qty-btn"
                    onclick="this.parentNode.querySelector('input[type=number]').stepDown()">
                    <i class="fas fa-minus"></i>
                  </button>


                  <div class="form-outline">

                    <input id="form1" min="0" name="quantity" value="1" type="number" class="form-control" />

                  </div>

                  <button class="btn btn-primary px-3 ms-2 qty-btn"
                    onclick="this.parentNode.querySelector('input[type=number]').stepUp()">
                    <i class="fas fa-plus"></i>
                  </button>
                </div>
                <!-- Quantity -->

                <!-- Price -->
                <p class="text-start text-md-center">
                  <strong id='front-price'><%= number_to_currency @listing.price %></strong>
                </p>
                <button class='btn btn-primary' id='fakeCommit'>Commit</button>

                <!-- Price -->
              </div>
            </div>
            <!-- Single item -->

            <hr class="my-4" />
        </div>
        
<%= form_with(model: [@listing, stock]) do |form| %>
<div class='d-none'>
  <%= form.hidden_field :user_id, value: current_user.id %>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity, min: 1,value:1 %>
  </div>

  <div>
    <%= form.submit id: 'buyCommit'  %>
  </div>
<% end %>
</div>
      </div>
    </div>
  </div>
</section>
</main>

      <%= javascript_include_tag "buy"  %>    

app/views/stocks/_stock.html.erb
<div id="<%= dom_id stock %>">
    <p><%= stock.listing.name %><p/>
    <p><%= stock.listing.ticker %><p/>
    <p><%= stock.listing.price %><p/>
    <p>Quantity: <%= stock.quantity %></p>
    <p>Owner: <%= User.find(stock.user_id).email %></p>
</div>

app/views/stocks/buy.html.erb

<% if @existing %>



<%= stylesheet_link_tag "dashboard", "data-turbo-track": "reload" %>

 <body>
    
<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#"><span>Hi </span><%= current_user.first_name.capitalize %>!</a>
  <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <input id='myInput' onkeyup="myFunction()" class="form-control form-control-dark w-100" type="text" placeholder="Search by Stock Name" aria-label="Search">

  <div class="navbar-nav">
    <div class="nav-item text-nowrap">
       <%= button_to "Log out", destroy_user_session_path, :method => :delete, class:'nav-link px-3 btn' %>
    </div>
  </div>
</header>

<div class="container-fluid">
  <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="position-sticky pt-3">

      <% if current_user.role == 'trader'%>
        <ul class="nav flex-column">
        <li class="nav-item">
            <%= link_to root_path, class:'nav-link' do %>
              <span data-feather="home"></span>
              Dashboard
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to portfolio_path, class: "nav-link" do%>
              <span data-feather="file"></span>
              Portfolio
             <%end%>
          </li>
           <li class="nav-item">
            <%= link_to listings_path, class: "nav-link" do%>
              <span data-feather="file"></span>
              Listings
             <%end%>
          </li>
           <li class="nav-item">
            <%= link_to transactions_path, class: "nav-link" do%>
              <span data-feather="file"></span>
              Transaction History
             <%end%>
          </li>
          <li class="nav-item">
          <%= link_to balance_path, class: "nav-link" do%>
            <span data-feather="dollar-sign"></span>
              Balance 
            <span data-feather="plus-circle"></span>
            <span><%= number_to_currency current_user.balance %></span>
            <%end%>
          </li>
        </ul>
        <%end%>

        <% if current_user.role == 'admin' %>
        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
          <span>Admin</span>
        </h6>
        <ul class="nav flex-column mb-2">
          <li class="nav-item">
             <a class="nav-link" href="/#pendingUser">
              <span data-feather="users"></span>
              <span>Pending Users</span>
              <span class="position-absolute end-5px pending"><%= get_pending_users %></span>
            </a>
          </li>
          <li class="nav-item">
              <a class="nav-link" href="/new">
              <span data-feather="users"></span>
              Create a Trader
            </a>
          </li>
          <li class="nav-item">
            <%= link_to transactions_path, class: 'nav-link' do%>
              <span data-feather="file-text"></span>
              Transactions
            <%end%>
          </li>
        </ul>
        <% end %>
      </div>
    </nav>

    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
<h1><%= @listing.name%></h1>
    
      </div>

      <div id='fundsError' class='d-none justify-content-center align-item-center'>
     <span class='text-danger fw-bold '>Insufficient Funds!</span>
     </div>

<section class="h-100 gradient-custom">
  <div class="container py-5">
    <div class="row d-flex justify-content-center my-4">
      <div class="col-md-8">
        <div class="card mb-4">
          <div class="card-header py-3">
            <h5 class="mb-0">You are <span class='btn btn-primary'> Buying </span> </h5>
            
          </div>
          <div class="card-body">
            <!-- Single item -->
            <div class="row">
              <div class="col-lg-3 col-md-12 mb-4 mb-lg-0">
                <!-- Image -->
                <div class="bg-image hover-overlay hover-zoom ripple rounded" data-mdb-ripple-color="light">
                  <img src="<%= @listing.logo %>"
                    class="w-100" alt="Blue Jeans Jacket" />
                  <a href="#!">
                    <div class="mask" style="background-color: rgba(251, 251, 251, 0.2)"></div>
                  </a>
                </div>
                <!-- Image -->
              </div>

              <div class="col-lg-5 col-md-6 mb-4 mb-lg-0">
                <!-- Data -->
                <p><strong><%= @listing.ticker%></strong></p>
                <p>Earning Ratio: <span class='bg-success text-white px-2 py-1 rounded fw-bold'><%= @listing.pe_ratio %></span></p>
                <p>Price: <span id='staticPrice'><%= number_to_currency @listing.price%></span></p>
                <p>Previous Price: <%= number_to_currency @listing.previous_close%></p>
          
               
                <!-- Data -->
              </div>

              <div class="col-lg-4 col-md-6 mb-4 mb-lg-0 d-flex flex-column justify-content-center">
                <!-- Quantity -->

       
                <div class="d-flex mb-4" style="max-width: 300px">
                  <button class="btn btn-primary px-3 me-2 qty-btn"
                    onclick="this.parentNode.querySelector('input[type=number]').stepDown()">
                    <i class="fas fa-minus"></i>
                  </button>


                  <div class="form-outline">

                    <input id="form1" min="0" name="quantity" value="1" type="number" class="form-control" />

                  </div>

                  <button class="btn btn-primary px-3 ms-2 qty-btn"
                    onclick="this.parentNode.querySelector('input[type=number]').stepUp()">
                    <i class="fas fa-plus"></i>
                  </button>
                </div>
                <!-- Quantity -->

                <!-- Price -->
                <p class="text-start text-md-center">
                  <strong id='front-price'><%= number_to_currency @listing.price %></strong>
                </p>
                <button class='btn btn-primary' id='fakeCommit'>Commit</button>

                <!-- Price -->
              </div>
            </div>
            <!-- Single item -->

            <hr class="my-4" />
            <span class='bg-warning px-2 rounded fw-bold text-white'>Owned <%= current_user.stocks.where(listing_id:@listing.id).first.quantity %></span>

    <%= form_with url: listing_stock_path(params[:listing_id], @stock.id), method: :patch do |f| %>
        <div class='d-none'>
        <div class="field">
            <%= f.label :quantity %>
            <%= f.number_field :quantity, min: 1,value:1 %>
        </div>

        <%= f.hidden_field :transaction_type, value: 'buy' %>

        <div>
            <%= f.submit id: 'buyCommit' %>
        </div>
        </div>
    <% end %>  

        </div>
      </div>
    </div>
  </div>
</section>
</main>


<%= javascript_include_tag "buyExist"  %>    

<% else %>
    <%= render "stocks/form", stock: @stock_build %>

<% end %>



    <script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js" integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE" crossorigin="anonymous"></script><script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js" integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha" crossorigin="anonymous"></script>

      <%= javascript_include_tag "dashboard"  %>    

app/views/stocks/edit.html.erb
<h1>Editing stock</h1>

<%= render "form", stock: @stock %>

<br>

<div>
  <%= link_to "Show this stock", listing_stock_path(@listing, @stock) %> |
  <%= link_to "Back to stocks", listing_stocks_path(@listing) %>
</div>

app/views/stocks/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Stocks</h1>

<div id="stocks">
  <% @stocks.each do |stock| %>
    <%= render stock %>
    <p>
      <%= link_to "Show this stock", listing_stock_path(@listing, stock) %>
    </p>
  <% end %>
</div>

<%= link_to "Buy", buy_stock_path(@listing.id) %><br/>
<%= link_to "Sell", sell_stock_path(@listing.id) %>

app/views/stocks/new.html.erb
<h1>New stock</h1>

<%= render "form", stock: @stock %>

<br>

<div>
  <%= link_to "Back to stocks", listing_stocks_path(@listing) %>
</div>

app/views/stocks/sell.html.erb




<%= stylesheet_link_tag "dashboard", "data-turbo-track": "reload" %>

 <body>

<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#"><span>Hi </span><%= current_user.first_name.capitalize %>!</a>
  <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <input id='myInput' onkeyup="myFunction()" class="form-control form-control-dark w-100" type="text" placeholder="Search by Stock Name" aria-label="Search">

  <div class="navbar-nav">
    <div class="nav-item text-nowrap">
       <%= button_to "Log out", destroy_user_session_path, :method => :delete, class:'nav-link px-3 btn' %>
    </div>
  </div>
</header>

<div class="container-fluid">
  <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="position-sticky pt-3">

      <% if current_user.role == 'trader'%>
        <ul class="nav flex-column">
        <li class="nav-item">
            <%= link_to root_path, class:'nav-link' do %>
              <span data-feather="home"></span>
              Dashboard
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to portfolio_path, class: "nav-link" do%>
              <span data-feather="file"></span>
              Portfolio
             <%end%>
          </li>
           <li class="nav-item">
            <%= link_to listings_path, class: "nav-link" do%>
              <span data-feather="file"></span>
              Listings
             <%end%>
          </li>
           <li class="nav-item">
            <%= link_to transactions_path, class: "nav-link" do%>
              <span data-feather="file"></span>
              Transaction History
             <%end%>
          </li>
          <li class="nav-item">
          <%= link_to balance_path, class: "nav-link" do%>
            <span data-feather="dollar-sign"></span>
              Balance 
            <span data-feather="plus-circle"></span>
            <span><%= number_to_currency current_user.balance %></span>
            <%end%>
          </li>
        </ul>
        <%end%>

        <% if current_user.role == 'admin' %>
        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
          <span>Admin</span>
        </h6>
        <ul class="nav flex-column mb-2">
          <li class="nav-item">
             <a class="nav-link" href="/#pendingUser">
              <span data-feather="users"></span>
              <span>Pending Users</span>
              <span class="position-absolute end-5px pending"><%= get_pending_users %></span>
            </a>
          </li>
          <li class="nav-item">
              <a class="nav-link" href="/new">
              <span data-feather="users"></span>
              Create a Trader
            </a>
          </li>
          <li class="nav-item">
            <%= link_to transactions_path, class: 'nav-link' do%>
              <span data-feather="file-text"></span>
              Transactions
            <%end%>
          </li>
        </ul>
        <% end %>
      </div>
    </nav>

    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
<h1><%= @listing.name%></h1>
    
      </div>


<section class="h-100 gradient-custom">
  <div class="container py-5">
    <div class="row d-flex justify-content-center my-4">
      <div class="col-md-8">
        <div class="card mb-4">
          <div class="card-header py-3">
            <h5 class="mb-0">You are <span class='btn btn-danger'> Selling </span></h5>
          </div>
          <div class="card-body">
            <!-- Single item -->
            <div class="row">
              <div class="col-lg-3 col-md-12 mb-4 mb-lg-0">
                <!-- Image -->
                <div class="bg-image hover-overlay hover-zoom ripple rounded" data-mdb-ripple-color="light">
                  <img src="<%= @listing.logo %>"
                    class="w-100" alt="Blue Jeans Jacket" />
                  <a href="#!">
                    <div class="mask" style="background-color: rgba(251, 251, 251, 0.2)"></div>
                  </a>
                </div>
                <!-- Image -->
              </div>

              <div class="col-lg-5 col-md-6 mb-4 mb-lg-0">
                <!-- Data -->
                <p><strong><%= @listing.ticker%></strong></p>
                <p>Earning Ratio: <span class='bg-success text-white px-2 py-1 rounded fw-bold'><%= @listing.pe_ratio %></span></p>
                <p>Price: <span id='staticPrice'><%= number_to_currency @listing.price%></span></p>
                <p>Previous Price: <%= number_to_currency @listing.previous_close%></p>
          
               
                <!-- Data -->
              </div>

              <div class="col-lg-4 col-md-6 mb-4 mb-lg-0 d-flex flex-column justify-content-center">
                <!-- Quantity -->


                <div class="d-flex mb-4" style="max-width: 300px">
                  <button class="btn btn-primary px-3 me-2 qty-btn"
                    onclick="this.parentNode.querySelector('input[type=number]').stepDown()">
                    <i class="fas fa-minus"></i>
                  </button>


                  <div class="form-outline">

                    <input id="form1" min="0" name="quantity" value="1" type="number" class="form-control"/>

                  </div>

                  <button class="btn btn-primary px-3 ms-2 qty-btn"
                    onclick="this.parentNode.querySelector('input[type=number]').stepUp()">
                    <i class="fas fa-plus"></i>
                  </button>
                </div>
                <!-- Quantity -->

                <!-- Price -->
                <p class="text-start text-md-center">
                  <strong id='front-price'><%= number_to_currency @listing.price %></strong>
                </p>
                <button class='btn btn-danger' id='fakeCommit'>Sell</button>

                <!-- Price -->
              </div>
            </div>
            <!-- Single item -->

            <hr class="my-4" />
            <span class='bg-warning px-2 rounded fw-bold text-white'>Owned <%= current_user.stocks.where(listing_id:@listing.id).first.quantity %></span>
        </div>
        
<%= form_with url: listing_stock_path(params[:listing_id], @stock.id), method: :patch do |f| %>

<div class='d-none'>
    <div class="field">
        <%= f.label :quantity %>
        <%= f.number_field :quantity, min: 1, max: @stock.quantity.to_s %>
    </div>

    <%= f.hidden_field :transaction_type, value: 'sell' %>
    <span id='maxSellQty'><%= @stock.quantity.to_s %></span>
    <div>
        <%= f.submit  id: 'sell' %>
    </div>

<% end %>  
      </div>
      </div>
    </div>
  </div>
</section>
</main>

      <%= javascript_include_tag "sell"  %>    



app/views/stocks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @stock %>

<div>
  <%= link_to "Edit this stock", edit_listing_stock_path(@listing, @stock) %> |
  <%= link_to "Back to stocks", listing_stocks_path(@listing) %>

  <%= button_to "Destroy this stock", [@listing, @stock], method: :delete, data: { confirm: 'Are you sure?' } %>
</div>