config/routes.rb
Rails.application.routes.draw do  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html  
  # Defines the root path route ("/")
  # root "articles#index"
  
  devise_for :users
  
  resources :listings do
    resources :stocks
  end

  root to: 'pages#index'  

  get   '/portfolio' => 'pages#portfolio', as: 'portfolio'
  get   '/new' => 'pages#new', as: 'new_trader'
  get   '/user/:id' => 'pages#show', as: 'user'
  patch '/user/:id' => 'pages#update'
  get   '/user/:id/edit' => 'pages#edit', as: 'user_edit'
  post  '/' => 'pages#create'  
  get   '/confirm_user/:trader_id' => 'pages#confirm_user', as: 'confirm_user'
  get   '/balance' => 'pages#balance', as: 'balance'
  patch '/balance' => 'pages#add_money'

  get   '/listings/:listing_id/buy', to: 'stocks#buy', as: 'buy_stock'
  get   '/listings/:listing_id/sell', to: 'stocks#sell', as: 'sell_stock'

  get   '/trader/transactions' => 'transactions#index', as: 'transactions'
  get   '/trader/transactions/:id' => 'transactions#show', as: 'transaction'
  
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user

end

app/views/pages/balance.html.erb





<%= stylesheet_link_tag "dashboard", "data-turbo-track": "reload" %>

 <body>
    
<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#"><span>Hi </span><%= current_user.first_name.capitalize %>!</a>
  <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="navbar-nav">
    <div class="nav-item text-nowrap">
       <%= button_to "Log out", destroy_user_session_path, :method => :delete, class:'nav-link px-3 btn' %>
    </div>
  </div>
</header>

<div class="container-fluid">
  <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="position-sticky pt-3">

      <% if current_user.role == 'trader'%>
        <ul class="nav flex-column">
          <li class="nav-item">
            <%= link_to root_path, class:'nav-link' do %>
              <span data-feather="home"></span>
              Dashboard
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to portfolio_path, class: "nav-link" do%>
              <span data-feather="file"></span>
              Portfolio
             <%end%>
          </li>
             <li class="nav-item">
            <%= link_to listings_path, class: "nav-link" do%>
              <span data-feather="file"></span>
              Listings
             <%end%>
          </li>
           <li class="nav-item">
            <%= link_to transactions_path, class: "nav-link" do%>
              <span data-feather="file"></span>
              Transaction History
             <%end%>
          </li>
          <li class="nav-item">
          <%= link_to balance_path, class: "nav-link" do%>
            <span data-feather="dollar-sign"></span>
              Balance 
            <span data-feather="plus-circle"></span>
            <span><%= number_to_currency current_user.balance %></span>
            <%end%>
          </li>
        </ul>
        <%end%>

        <% if current_user.role == 'admin' %>
        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
          <span>Admin</span>
        </h6>
        <ul class="nav flex-column mb-2">
          <li class="nav-item">
             <a class="nav-link" href="/#pendingUser">
              <span data-feather="users"></span>
              <span>Pending Users</span>
              <span class="position-absolute end-5px pending"><%= get_pending_users %></span>
            </a>
          </li>
          <li class="nav-item">
              <a class="nav-link" href="/new">
              <span data-feather="users"></span>
              Create a Trader
            </a>
          </li>
          <li class="nav-item">
            <%= link_to transactions_path, class: 'nav-link' do%>
              <span data-feather="file-text"></span>
              Transactions
            <%end%>
          </li>
      
        </ul>

        <% end %>



      </div>
    </nav>

    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
<h1>Current Balance: <%= number_to_currency @balance || 0 %></h1>
          </div>
<%= form_with url: '/balance', method: :patch do |f| %>

  <div class="field row">
  <div class='col-lg-4'>
    <%= f.label :balance %><br />
    <%= f.number_field :balance, autofocus: true, min: 1, step: :any, class:'form-control mt-2', required: true %>
  <div>
  </div>
  <div class="actions">
    <%= f.submit "Load Balance",class:'btn btn-primary mt-4' %>
  </div>
  
<% end %>



    </main>
  </div>
  
</div>







    <script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js" integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE" crossorigin="anonymous"></script><script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js" integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha" crossorigin="anonymous"></script>

      <%= javascript_include_tag "dashboard"  %>    


app/views/pages/index.html.erb
<%= stylesheet_link_tag "dashboard", "data-turbo-track": "reload" %>

 <body>
    
<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#"><span>Hi </span><%= current_user.first_name.capitalize %>!</a>
  <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
    <% if current_user.role == 'admin'%>
  <input id='myInput' onkeyup="myFunction()" class="form-control form-control-dark w-100" type="text" placeholder="Search All Traders by Name" aria-label="Search">
  <%else%>
   <div id='myInput'class="bg-dark w-100" type="text" placeholder="" ></div>
    <%end%>
  <div class="navbar-nav">

    <div class="nav-item text-nowrap">
       <%= button_to "Log out", destroy_user_session_path, :method => :delete, class:'nav-link px-3 btn' %>
    </div>
  </div>
</header>

<div class="container-fluid">
  <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="position-sticky pt-3">

      <% if current_user.role == 'trader'%>
        <ul class="nav flex-column">
       <li class="nav-item">
            <%= link_to root_path, class:'nav-link' do %>
              <span data-feather="home"></span>
              Dashboard
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to portfolio_path, class: "nav-link" do%>
              <span data-feather="file"></span>
              Portfolio
             <%end%>
          </li>
             <li class="nav-item">
            <%= link_to listings_path, class: "nav-link" do%>
              <span data-feather="file"></span>
              Listings
             <%end%>
          </li>
          <li class="nav-item">
           <li class="nav-item">
            <%= link_to transactions_path, class: "nav-link" do%>
              <span data-feather="file"></span>
              Transaction History
             <%end%>
          </li>
          <%= link_to balance_path, class: "nav-link" do%>
            <span data-feather="dollar-sign"></span>
              Balance 
            <span data-feather="plus-circle"></span>
            <span><%= number_to_currency current_user.balance %></span>
            <%end%>
          </li>
        </ul>
        <%end%>

        <% if current_user.role == 'admin' %>
        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
        <%= link_to root_path do %>
          <span>Admin</span>
          <% end %>
        </h6>
        <ul class="nav flex-column mb-2">
          <li class="nav-item">
             <a class="nav-link" href="#pendingUser">
              <span data-feather="users"></span>
              <span>Pending Users</span>
              <span class="position-absolute end-5px pending"><%= @users_pending.count %></span>
            </a>
          </li>
          <li class="nav-item">
              <a class="nav-link" href="/new">
              <span data-feather="users"></span>
              Create a Trader
            </a>
          </li>
          <li class="nav-item">
            <%= link_to transactions_path, class: 'nav-link' do%>
              <span data-feather="file-text"></span>
              Transactions
            <%end%>
          </li>
      
        </ul>

        <% end %>



      </div>
    </nav>

    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Dashboard <%= "/ #{current_user.role.capitalize}"%></h1>
    
      </div>


<%if current_user.role == 'trader'%>
<div class='my-5'>
<h2>Hot Picks</h2>
<div class="row">

<% get_top_listings.each do |listing|%>
  <div class="col mt-3">
    <div class="card">
      <div class="card-body">
        <img src='<%= listing.logo %>' width='50px' class='mb-2'>
        <h2 class="card-title"><%= listing.name %></h2>
        <p class="card-text m-0">Value: <span class='bg-success text-white px-2 py-1 rounded fw-bold'><%= '$'+ number_to_human(listing.market_cap) %></span></p>
        <p class="card-text m-0">Previous Close: <span><%= number_to_currency(listing.previous_close) %></span></p>
        <p class="card-text ">Price: <span><%= '$'+ number_to_human(listing.price) %></span></p>

        <%= link_to buy_stock_path(listing.id), class:"btn btn-primary" do %>
          Buy
          <% end %>
      </div>
      <canvas class="my-4 w-100 mychart" id="myChart" ></canvas> 
    </div>
  </div>
<% end %>

</div>
</div>
<% end %>


     <% if current_user.role == 'admin'%>

      <div class="my-5">
      <h2>All Traders</h2>
      <div class="table-responsive ">
        <table id='myTable' class="table table-striped table-sm ">
         
            <tr>
              <th scope="col">Name </i></th>
              <th scope="col">Wallet</th>
              <th scope="col">Total Stocks</th>
              <th scope="col">Total Stock Value</th>
              <th scope="col">Last Trade</th>
            </tr>
     
          <% if @users_approve != nil %>
          <% @users_approve.each do |user| %>

            <tr>

              <td><%= link_to "#{user.last_name.capitalize}, #{user.first_name.capitalize}", user_path(user.id) %> </td>
         
              <td><%=  number_to_currency user.balance %></td>
              <td><%= user.stocks.count %></td>
              <td><%= get_total_stock_value(user.id) %></td>
              <td><%= get_user_last_trade(user.id) %></td>
            </tr>
    
          <% end %>
          <%else %>

            <h2>No Traders found<h2>
          <% end %>

        </table>
        </div> <% end %>

      <div class="my-5">
      <h2>Recent Transactions</h2>
      <div class="table-responsive ">
        <table class="table table-striped table-sm ">
 
            <tr>
              <th scope="col">Ref</th>
              <th scope="col">Trader</th>
              <th scope="col">Stock Name</th>
              <th scope="col">Type</th>
              <th scope="col">Date</th>
              <th scope="col">Qty</th>
              <th scope="col">Amount</th>
            </tr>
   
<% if get_recent_trans(current_user.role)!= nil %>
          <% get_recent_trans(current_user.role).each do |trans| %>
   
            <tr>
              <td><%= trans.id %></td>
              <td><%=  trans.user.last_name.capitalize + ", " +trans.user.first_name.capitalize  %></td>
              <td><%= trans.name %></td>
              <td><%= trans.transaction_type %></td>
              <td><%= trans.created_at%></td>
              <td><%= trans.quantity %></td>
              <td>  <%= number_to_currency trans.price %></td>
            </tr>
          <% end %>
           <% else %>
           <h2>No transactions <h2>
             <% end %>

        </table>
        </div>
      </div>


<% if current_user.role == 'admin' %>
  <div id="pendingUser" class="my-5">
    <h2>Pending Users</h2>
    <div  class="d-flex gap-5 flex-wrap justify-content-center">
        <% @users_pending.each do |user|%>
          <div class="card" style="width: 18rem;">
            <div class="card-body">
              <h5 class="card-title"><%= user.email %></h5>
              <p class="card-text"><%= "#{user.first_name} #{user.last_name} "%></p>
              <a href="/confirm_user/<%=user.id%>" class="btn btn-primary">Approve</a>
            </div>
          </div>
        <% end %>    
      </div>
    </div>
    <% end %>

    </main>
  </div>
  
</div>







    <script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js" integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE" crossorigin="anonymous"></script><script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js" integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha" crossorigin="anonymous"></script>

      <%= javascript_include_tag "dashboard"  %>    

app/views/pages/portfolio.html.erb




<%= stylesheet_link_tag "dashboard", "data-turbo-track": "reload" %>

 <body>
    
<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#"><span>Hi </span><%= current_user.first_name.capitalize %>!</a>
  <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
    <div id='myInput'class="bg-dark w-100" type="text" placeholder="" ></div>
  <div class="navbar-nav">
    <div class="nav-item text-nowrap">
       <%= button_to "Log out", destroy_user_session_path, :method => :delete, class:'nav-link px-3 btn' %>
    </div>
  </div>
</header>

<div class="container-fluid">
  <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="position-sticky pt-3">

      <% if current_user.role == 'trader'%>
        <ul class="nav flex-column">
         <li class="nav-item">
            <%= link_to root_path, class:'nav-link' do %>
              <span data-feather="home"></span>
              Dashboard
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to portfolio_path, class: "nav-link" do%>
              <span data-feather="file"></span>
              Portfolio
             <%end%>
          </li>
        <li class="nav-item">
            <%= link_to listings_path, class: "nav-link" do%>
              <span data-feather="file"></span>
              Listings
             <%end%>
          </li>
           <li class="nav-item">
            <%= link_to transactions_path, class: "nav-link" do%>
              <span data-feather="file"></span>
              Transaction History
             <%end%>
          </li>
          <li class="nav-item">
          <%= link_to balance_path, class: "nav-link" do%>
            <span data-feather="dollar-sign"></span>
              Balance 
            <span data-feather="plus-circle"></span>
            <span><%= number_to_currency current_user.balance %></span>
            <%end%>
          </li>
        </ul>
        <%end%>

        <% if current_user.role == 'admin' %>
        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
          <span>Admin</span>
        </h6>
        <ul class="nav flex-column mb-2">
          <li class="nav-item">
             <a class="nav-link" href="/#pendingUser">
              <span data-feather="users"></span>
              <span>Pending Users</span>
              <span class="position-absolute end-5px pending"><%= get_pending_users %></span>
            </a>
          </li>
          <li class="nav-item">
              <a class="nav-link" href="/new">
              <span data-feather="users"></span>
              Create a Trader
            </a>
          </li>
          <li class="nav-item">
            <%= link_to transactions_path, class: 'nav-link' do%>
              <span data-feather="file-text"></span>
              Transactions
            <%end%>
          </li>
      
        </ul>

        <% end %>



      </div>
    </nav>

    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
<h1>Portfolio Page</h1>
    
</div>

<div class='row'>
  <div class=' col-lg-6 mt-4'>
    <div class='rounded mx-auto d-flex align-items-center justify-content-around' >
      <div>
        <span data-feather="activity"></span>
      </div>
      <div class='fw-bold text-center'>
      <p>Total Asset</p>
        <%= get_total_stock_value current_user.id %>
      </div>
    </div>
  </div>
  <div class='col-lg-6  mt-4'>
   <div class='mx-auto d-flex align-items-center justify-content-around' >
      <div>
        <span data-feather="package"></span>
      </div>
      <div class='fw-bold text-center'>
      <p>Stock Owned</p>
        <%= current_user.stocks.count %>
      </div>
    </div>
  </div>
</div>


<div class='container'>
<div class='row'>

<% @stocks.each do |stock|%>

  <div class="mt-3">
    <div class="card ">
<div class='row'>

      <div class="card-body col-lg-6 d-flex flex-column text-center">
        <img src='<%= stock.listing.logo %>' width='150px' class='mb-2 mx-auto'>
        <h2 class="card-title"><%= stock.listing.name %></h2>
        <p class="card-text my-1">Owned $: <span class=' bg-success text-white px-2 py-1 rounded fw-bold'><%= number_to_currency stock.quantity * stock.listing.price %></span></p>
        <p class="card-text my-1">Quantity: <span class='bg-warning text-white px-2 py-1 rounded fw-bold'><%= stock.quantity %></span></p>
        <p class="card-text my-1">Market Price: <span class='bg-danger text-white px-2 py-1 rounded fw-bold'><%= number_to_currency stock.listing.price %></span></p>
        <p class="card-text my-1">Last Trade: <span class=''><%= last_trade_stock(stock.listing.ticker) %></span></p>



        <div class='row'>
        <div class='col-lg-6'>
        <%= link_to buy_stock_path(stock.listing.id), class:"btn btn-primary mt-3" do %>
          Buy
          <% end %>
          </div>
        <div class='col-lg-6'>
        <%= link_to sell_stock_path(stock.listing.id), class:"btn btn-danger mt-3" do %>
          Sell
          <% end %>
          </div>
          </div>
      </div>
      <div class='col col-lg-6 d-flex align-items-center'>
      <canvas class="my-6 w-100 mychart" id="myChart" ></canvas> 
      </div>
      </div>
    </div>
  </div>
<% end %>
</div>
</div>
</div>


    </main>
  </div>
  
</div>







    <script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js" integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE" crossorigin="anonymous"></script><script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js" integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha" crossorigin="anonymous"></script>

      <%= javascript_include_tag "dashboard"  %>    


app/views/pages/show.html.erb

<%= stylesheet_link_tag "dashboard", "data-turbo-track": "reload" %>

 <body>
    
<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#"><span>Hi </span><%= current_user.first_name.capitalize %>!</a>
  <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="navbar-nav">
    <div class="nav-item text-nowrap">
       <%= button_to "Log out", destroy_user_session_path, :method => :delete, class:'nav-link px-3 btn' %>
    </div>
  </div>
</header>

<div class="container-fluid">
  <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="position-sticky pt-3">

      <% if current_user.role == 'trader'%>
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">
              <span data-feather="home"></span>
              Dashboard
            </a>
          </li>
          <li class="nav-item">
            <%= link_to portfolio_path, class: "nav-link" do%>
              <span data-feather="file"></span>
              Portfolio
             <%end%>
          </li>
          <li class="nav-item">
          <%= link_to balance_path, class: "nav-link" do%>
            <span data-feather="dollar-sign"></span>
              Balance 
            <span data-feather="plus-circle"></span>
            <span><%= number_to_currency current_user.balance %></span>
            <%end%>
          </li>
        </ul>
        <%end%>

        <% if current_user.role == 'admin' %>
        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
            <%= link_to root_path do %>
          <span>Admin</span>
          <% end %>
        </h6>
        <ul class="nav flex-column mb-2">
          <li class="nav-item">
             <a class="nav-link" href="/#pendingUser">
              <span data-feather="users"></span>
              <span>Pending Users</span>
              <span class="position-absolute end-5px pending"><%= get_pending_users %></span>
            </a>
          </li>
          <li class="nav-item">
              <a class="nav-link" href="/new">
              <span data-feather="users"></span>
              Create a Trader
            </a>
          </li>
          <li class="nav-item">
            <%= link_to transactions_path, class: 'nav-link' do%>
              <span data-feather="file-text"></span>
              Transactions
            <%end%>
          </li>
      
        </ul>

        <% end %>



      </div>
    </nav>

    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1><%= @user.last_name + ', '+ @user.first_name %> </h1>
    
      </div>

      

    <div class='container'>
        <div class='row'>
            <div class='col-lg-6 '>
             <h2>Trade Information</h2>
               <p> Balance: <span></span><%=  number_to_currency @user.balance %></span></p>
               <p> Total Stocks: <%= @user.stocks.count %></p>
               <p> Total Stocks Value: <%= get_total_stock_value(@user.id) %></p>
               <p> Last Trade: <%= get_user_last_trade(@user.id) %></p>
            </div>
            <div class='col-lg-6'>   
            <div class='d-flex justfy-content-between gap-5'><h2>Account Information</h2> <%= button_to "Delete", admin_destroy_user_path(id:@user.id), method: :delete,class:'btn btn-danger',form: {data: {turbo_confirm: "This Action will delete all data related to user - #{@user.last_name + ', ' + @user.first_name }"}}%></div>
               <p> Email: <span></span><%= email_encrypt @user.email %></span></p>
               <p> Full Name <%= @user.last_name  + ', ' + @user.first_name %></p>
                <p> Password: ********* </p>
            <%= link_to 'Edit', user_edit_path(id:@user.id), class:'btn btn-primary'%>
            </div>
        </div>
    </div>
   
      
   </main>
  </div>
  
</div>







    <script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js" integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE" crossorigin="anonymous"></script><script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js" integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha" crossorigin="anonymous"></script>

      <%= javascript_include_tag "dashboard"  %>    
